In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
import pandas as pd
pd.__version__

'1.2.4'

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [7]:
bmw = df[df['Make'] == 'BMW']

In [8]:
bmw.MSRP.mean()

61546.76347305389

In [9]:
subset_2015 = df[df['Year'] >= 2015]
subset_2015

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11898   BMW          Z4  2015     premium unleaded (required)      300.0   
11899   BMW          Z4  2015     premium unleaded (required)      335.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11898               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11899               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11898  Luxury,High-Performance      Compact   Convertible           24   
11899  Luxury,High-Performance      Compact   Convertible           24   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11898        17        3916  56950  
11899        17        3916  65800  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[5995 rows x 16 columns]

In [10]:
subset_2015[subset_2015['Engine HP'].isnull()].shape

(51, 16)

In [11]:
mean_hp_before = df['Engine HP'].mean()

In [13]:
df["Engine HP"] = df["Engine HP"].fillna(mean_hp_before)

In [14]:
mean_hp_after = df['Engine HP'].mean()

In [15]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


In [16]:
rolls_royce = df[df['Make'] == "Rolls-Royce"]

In [17]:
some_columns = rolls_royce[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [18]:
some_columns = some_columns.drop_duplicates()
some_columns

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [19]:
x = some_columns.values
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [20]:
xtx = np.dot(x.T, x)
xtx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [21]:
xtx_invert = np.linalg.inv(xtx)
xtx_invert.sum()

0.032212320677486125

In [22]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [23]:
w = np.dot(xtx_invert, x.T)

In [24]:
w = np.dot(w, y)
w

array([ 0.19989598, 31.02612262, 31.65378877])